[package]
name = "oracle-v2"
version = "1.0.0"
edition = "2021"

[dependencies]
scrypto = { version = "1.2.0" }

[dev-dependencies]

[features]
default = []
test = []

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
